### ISSUE TITLE
rename project to metadata?

### ISSUE THREAD

**Issue by nsheff** [pepkit/hello_looper#18]
Right now I like how the example folders all have 3 subfolders, called `data`, `pipeline`, and `project`.

But I bet for lots of people the `project` folder is confusing, since I kind of think of the parent folder as a "Looper project".

I suggest we rename the `project` folder to simply  `metadata`.

Then it's more clear what the components are. 

@donaldcampbelljr what do you think?

**Comment by donaldcampbelljr** [comment]
But within the project folder is a **PEP project**, and our looper documentation points to the PEP specification to clarify what that means. If we change it to metadata, then we will have two separate names for the same concept. If anything, shouldn't we rename the folder to pep_project? or PEP?

**Comment by nsheff** [comment]
this makes sense to you and I, but I doubt it makes sense to a newcomer. 'project' is a really generic term.

also it should be just "PEP" not "PEP project" (the final P is project).

changing to metadata doesn't use 2 separate names for the same concept -- it's removing the ambiguity by using the word 'project' for *neither*.

**Comment by donaldcampbelljr** [comment]
We changed project to metadata so this will be done with the above PR.
