### ISSUE TITLE
wc/cut error on mac

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/hello_looper#2]
The `hello_looper` example does not run on `macOS` as is. More precisely, the command: `wc -l` here: 

https://github.com/pepkit/hello_looper/blob/5c403af2cb98b4adc511539b4a974e4840b3d550/pipeline/count_lines.sh#L2

produces an error:

```
mstolarczyk@MichalsMBP:/Users/mstolarczyk/Uczelnia/UVA/code/hello_looper wc data/frog1_data.txt -l
       4       4      28 data/frog1_data.txt
wc: -l: open: No such file or directory
       4       4      28 total
```

moving the flag before the argument helps:

```
mstolarczyk@MichalsMBP:/Users/mstolarczyk/Uczelnia/UVA/code/hello_looper wc -l data/frog1_data.txt 
       4 data/frog1_data.txt
```

However, even if you fix that, the following `cut` command does not pick up the piped value.

```
mstolarczyk@MichalsMBP:/Users/mstolarczyk/Uczelnia/UVA/code/hello_looper wc -l data/frog1_data.txt | cut -f1 -d' '
```

Not sure if it happens just in my system, though.

**Comment by nsheff** [comment]
yeah we run into this repeatedly with macs. the mac puts a leading space in front. this is the same issue we've already had to correct in other areas (like @jpsmith5 did in ngstk).

**Comment by nsheff** [comment]
you should be able to use that same solution (add a pipe step to `sed`with, I think, `-e`)

**Comment by stolarczyk** [comment]
OK. This worked: `wc -l data/frog1_data.txt | sed -E 's/^[[:space:]]+//' | cut -f1 -d' '`
