### ISSUE TITLE
hello caravel

### ISSUE THREAD

**Issue by nsheff** [pepkit/hello_looper#3]
```
report_result() {
  echo "$1\t$2" > stats.tsv
}
```

```
report_object() {
  echo "$1\t$2" > objects.tsv
}
```

count_lines.sh
```
starttime = `date`
x = wc -l....
echo "num_lines\t$x" > stats.tsv
touch count_lines_running.flag
awk ... > dist.txt

R <<EOF
d = read.table("dist.txt")
png("length_dist.png")
hist(d)
dev.off()
EOF

echo "dist_file\length_dist.png" > objects.tsv
export time=`date`
delta = starttime-time
echo "Runtime\t$delta > stats.tsv
echo "Success\t$time" > stats.tsv

mv count_lines_runnning.flag count_lines_completed.flag
```

- [ ] a shell pipeline that works with caravel/looper reports/status (above psuedocode)
- [ ] add a project, so there are 2.
- [ ] second project has subprojects, 6-10 samples, data files that are longer with varying line lengths
- [ ] pipeline showcases a plot to demonstrate object

**Comment by donaldcampbelljr** [comment]
I believe this issue is outdated,  and some of the items have been addressed in our recent restructure of hello_looper, the looper docs and with the push towards looper v 2.0.0. Therefore, I will close it. Please reopen if you feel this needs more attention.
