### ISSUE TITLE
Add details for Hello World?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [pepkit/hello_looper#7]
Hello all, 

I was working through the `hello world` example listed [here](http://looper.databio.org/en/latest/hello-world/). 

I think there are a few assumptions made that make it not possible to run the example. 

1. The scripts cannot be submitted since they do not have any defaults set for the `time, CPU, and memory sbatch` variables . Hence, it would be useful to include info here about that. 
2. When I try to remedy the above problem by running `looper run --compute mem=1GB cores=1 time=1:00 project_config.yaml`, I get an error saying that `No project config defined and dotfile does not exist`. It's expecting a `.looper.yaml` file in the `./project/` folder. 

Just letting you know of this. 🙂

**Comment by donaldcampbelljr** [comment]
We've made major changes to the structure of this repository as well as the looper docs in preparation for Looper 2.0.0 release:
Prerelease: https://github.com/pepkit/looper/releases/tag/v2.0.0a2
Docs: https://pep.databio.org/looper/

Therefore, I will close this issue. Please let us know if there are still improvements you would like to see.
